### ISSUE TITLE
why though?

### ISSUE THREAD

**Issue by Krebsartig** [10maurycy10/liveoverflow-proxy#1]
![SCR-20221024-ssf](https://user-images.githubusercontent.com/83917104/197601661-76a4725b-a196-44f1-a0e0-a924f000bd60.png)

**Comment by 10maurycy10** [comment]
What command are you using? (redact the token ofc)

**Comment by Krebsartig** [comment]
I figured it out it was because of my pc I ran it on my Linux server and it works nowBeste Grüße David JessenOn 25. Oct 2022, at 00:02, 10maurycy10 ***@***.***> wrote:﻿
What command are you using? (redact the token ofc)
