### ISSUE TITLE
Readme link broken - Small issue

### ISSUE THREAD

**Issue by willcatmeow** [10maurycy10/liveoverflow-proxy#3]
The link on how to obtain your minecraft token is broken, it redirects to `https://github.com/10maurycy10/liveoverflow-proxy/blob/main/kqzz.github.io/mc-bearer-token` which doesn't exist, instead of `https://kqzz.github.io/mc-bearer-token/` the correct url.

**Comment by 10maurycy10** [comment]
Thanks for spotting. fixed.
